apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: banking-demo
  labels:
    app: ledger-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
      - name: ledger-service
        image: quay.io/mmartofe/banking-demo-ledger-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: banking-kafka-kafka-bootstrap.banking-infra.svc.cluster.local:9092
        - name: APICURIO_URL
          value: http://apicurio-registry.banking-infra.svc.cluster.local:8080
        - name: SOURCE_CLUSTER
          value: onprem
        - name: DATASOURCE_URL
          value: jdbc:postgresql://postgres-pgbouncer.banking-infra.svc.cluster.local:5432/postgres
        - name: DATASOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: user
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
      imagePullSecrets:
      - name: quay-pull-secret
