apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: banking-kafka
  namespace: openshift-gitops
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          cluster-role: onprem
      values:
        overlay: onprem
  - clusters:
      selector:
        matchLabels:
          cluster-role: cloud
      values:
        overlay: cloud
  template:
    metadata:
      name: 'banking-kafka-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mmartofel/rhacm-multi-cluster-scalability.git
        targetRevision: HEAD
        path: 'infra/kafka/overlays/{{values.overlay}}'
      destination:
        server: '{{server}}'
        namespace: banking-infra
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=false
