apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: banking-infra
  labels:
    app: apicurio-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
      - name: apicurio-registry
        image: quay.io/apicurio/apicurio-registry-kafkasql:2.5.11.Final
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: APICURIO_KAFKASQL_BOOTSTRAP_SERVERS
          value: banking-kafka-kafka-bootstrap.banking-infra.svc.cluster.local:9092
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      imagePullSecrets:
      - name: quay-pull-secret
