apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
  namespace: banking-infra
  labels:
    app: apicurio-registry
spec:
  selector:
    app: apicurio-registry
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
