apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: banking-mirror
  namespace: banking-infra
spec:
  version: 4.2.0
  replicas: 1
  target:
    bootstrapServers: banking-kafka-kafka-bootstrap.banking-infra.svc.cluster.local:9092
  mirrors:
  - source:
      bootstrapServers: kafka-bootstrap:9092
    topicsPattern: "transactions-.*"
    sourceConnector:
      config:
        replication.factor: "3"
        offset-syncs.topic.replication.factor: "3"
        sync.topic.acls.enabled: "false"
