apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "kafka-bootstrap.banking-infra.svc.cluster.local:9092"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "http://apicurio-registry.banking-infra.svc.cluster.local:8080"
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: "cloud"
    - op: replace
      path: /spec/template/spec/containers/0/env/4/value
      value: "jdbc:postgresql://postgresql-primary.banking-infra.svc.cluster.local:5432/postgres"
  target:
    kind: Deployment
    name: transaction-processor
- patch: |-
    - op: replace
      path: /spec/minReplicaCount
      value: 0
    - op: replace
      path: /spec/maxReplicaCount
      value: 20
    - op: replace
      path: /spec/triggers/0/metadata/bootstrapServers
      value: "kafka-bootstrap.banking-infra.svc.cluster.local:9092"
    - op: replace
      path: /spec/triggers/0/metadata/consumerGroup
      value: "transaction-processors-cloud"
  target:
    kind: ScaledObject
    name: transaction-processor
