apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-build
  namespace: banking-build
---
# privileged SCC required for buildah to write /proc/<pid>/uid_map
# when setting up user namespaces for OCI builds inside the cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: banking-build-pipeline-privileged
subjects:
- kind: ServiceAccount
  name: pipeline-build
  namespace: banking-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
