apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: transaction-processor
  namespace: banking-demo
spec:
  scaleTargetRef:
    name: transaction-processor
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 300
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: banking-kafka-kafka-bootstrap.banking-infra.svc.cluster.local:9092
      consumerGroup: transaction-processors-onprem
      topic: transactions-raw
      lagThreshold: "500"
      offsetResetPolicy: latest
