apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: cloud-ledger-service
  namespace: banking-demo
spec:
  routingKey: cloud-ledger-service
  port: 8080
  host: cloud-ledger-service
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: cloud-cluster-gateway
  namespace: banking-demo
spec:
  routingKey: cloud-cluster-gateway
  port: 8080
  host: cloud-cluster-gateway
