apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: "onprem"
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "0,1,2"
  target:
    kind: Deployment
    name: transaction-generator
