quarkus.application.name=ledger-service

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
quarkus.datasource.username=${DATASOURCE_USER:postgres}
quarkus.datasource.password=${DATASOURCE_PASSWORD:postgres}
quarkus.hibernate-orm.database.generation=none

# Kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.incoming.committed-in.connector=smallrye-kafka
mp.messaging.incoming.committed-in.topic=transactions-committed
mp.messaging.incoming.committed-in.group.id=ledger-updaters-${SOURCE_CLUSTER:unknown}
mp.messaging.incoming.committed-in.value.deserializer=io.apicurio.registry.serde.avro.AvroKafkaDeserializer
mp.messaging.incoming.committed-in.apicurio.registry.url=${APICURIO_URL:http://localhost:8081}/apis/registry/v2
mp.messaging.incoming.committed-in.auto.offset.reset=earliest

# Health
quarkus.smallrye-health.root-path=/health
